---
title: "Shiny App Test v3 can select year"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)

alldata <- read.csv('./REA_ASR_3846_final.csv', encoding = "UTF-8")
alldata$latitude <- jitter(alldata$latitude)
alldata$longitude <- jitter(alldata$longitude)
## we test this code using 1943 data
wholedata<- alldata %>%
  rename(year = X.U.FEFF.Year,
         Lat = latitude, 
         Long = longitude,
         EnergyConsump= kwh_per_cc1) %>%
  filter(!is.na(EnergyConsump), !is.na(min_stop_dist), !is.na(allo_all), !is.na(re_opm), !is.na(state), !is.na(county), !is.na(system), !is.na(op_me)) %>%
  select(year:system, Lat:allo_all, op_kwh_p, op_kwh_b, op_ccn,    re_opm, re_cpp) %>%
  select(-state) %>%
  rename(state= st_code) 

wholedata$Treat <- ifelse(wholedata$min_stop_dist<=20, 1, 0)

```

```{r}
## Make dataset shiny compatible
library(leaflet)
library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)
library(shiny)

server <- shinyServer(function(input, output, session) {
  
  ## Interactive Map ###########################################
  # Filter the dataset user wants to look at
  readata <- reactive({
    wholedata %>%
      filter(
        year == input$year
        )
  })
  
  # Create the base map
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles(
        urlTemplate = "//{s}.tiles.mapbox.com/v3/jcheng.map-5ebohr46/{z}/{x}/{y}.png",
        attribution = 'Maps by <a href="http://www.mapbox.com/">Mapbox</a>'
      ) %>%
      setView(lng = -93.85, lat = 37.45, zoom = 4)
  })
  
  # A reactive expression that returns the set of systems that are
  # in bounds right now
  MapsInBounds <- reactive({
    if (is.null(input$map_bounds))
      return(readata()[FALSE,])
    bounds <- input$map_bounds
    latRng <- range(bounds$north, bounds$south)
    lngRng <- range(bounds$east, bounds$west)
    
    subset(readata(),
           Lat >= latRng[1] & Lat <= latRng[2] &
             Long >= lngRng[1] & Long <= lngRng[2])
  })
  
  # Precalculate the breaks, min and max value, we'll need for the two histograms
  observe({
  Breaks <- hist(plot = FALSE, readata()$EnergyConsump, breaks = 20)$breaks
  min_ec <- min(readata()$EnergyConsump)
  max_ec <- max(readata()$EnergyConsump)
  min_dist <- min(readata()$min_stop_dist)
  max_dist <- max(readata()$min_stop_dist)

  output$histEnergy <- renderPlot({
    # If no zipcodes are in view, don't plot
    if (nrow(MapsInBounds()) == 0)
      return(NULL)

    hist(MapsInBounds()$EnergyConsump,
      breaks = Breaks,
      main = "Energy Consumption (visible systems)",
      xlab = "KWH",
      xlim = c(min_ec, max_ec),
      col = '#00DD00',
      border = 'white')
  })

  output$scatterStopEnergy <- renderPlot({
    # If no zipcodes are in view, don't plot
    if (nrow(MapsInBounds()) == 0)
      return(NULL)

    print(xyplot(EnergyConsump ~ min_stop_dist, data = MapsInBounds(), xlim = c(min_dist, max_dist), ylim = c(min_ec, max_ec), xlab = "Dist to Nearest Stop (Mile)", ylab= "KWH"))
    })
  
  })
  
    # This observer is responsible for maintaining the circles and legend,
  # according to the variables the user has chosen to map to color and size.
  session$onFlushed(once=TRUE, function() {
    paintObs <- observe({
    colorBy <- input$color
    sizeBy <- input$size

    if (colorBy == "Treat") {
      # Color and palette are treated specially in the "treat" case, because
      # the values are categorical instead of continuous.
      colorData <- ifelse(readata()$min_stop_dist<=input$threshold, "yes", "no")
      pal <- colorFactor("magma", colorData)
    } else {
      colorData <- readata()[[colorBy]]
      pal <- colorBin("magma", colorData, 5, pretty = FALSE)
    }

    radius <- readata()[[sizeBy]] / max(readata()[[sizeBy]]) * 30000
    
    observe({
    leafletProxy("map", data = readata()) %>%
      clearShapes() %>%
      addCircles(~Long, ~Lat, radius=radius, layerId=~system,
        stroke=FALSE, fillOpacity=0.5, fillColor=pal(colorData)) %>%
      addLegend("bottomleft", pal=pal, values=colorData, title=colorBy, layerId="colorLegend")
      })
    
    })
    
  session$onSessionEnded(paintObs$suspend)
  })
  
    # Show a popup at the given location
  showBorrowerPopup <- function(system, lat, lng) {
    observe({
    selectedsys <- readata()[readata()$system == system,]
    content <- as.character(tagList(
      tags$h4("System:", as.character(selectedsys$system)),
      tags$strong(HTML(sprintf("%s, %s %s",
        selectedsys$city, selectedsys$county, selectedsys$state
      ))), tags$br(),
      sprintf("Energy Consumption Per Residential Customer: %s", as.integer(selectedsys$EnergyConsump)), tags$br(),
      sprintf("Distance to Nearest Roadshow Stop: %s", as.integer(selectedsys$min_stop_dist)), tags$br(),
      sprintf("Total Allotment: %s", dollar(selectedsys$allo_all)), tags$br(),
      sprintf("Consumers Served: %s", as.integer(selectedsys$op_ccn)), tags$br(),
      sprintf("Operation Revenue: %s", as.integer(selectedsys$re_opm)), tags$br(),
      sprintf("Miles Energized: %s", as.integer(selectedsys$op_me))
    ))
    leafletProxy("map", data = readata()) %>% addPopups(lng, lat, content, layerId = system)
    })
  }

  # When map is clicked, show a popup with city info
clickObs <- observe({
    leafletProxy("map", data = readata()) %>% clearPopups()
    event <- input$map_shape_click
    if (is.null(event))
      return()

    isolate({
      showBorrowerPopup (event$id, event$lat, event$lng)
    })
  })

session$onSessionEnded(clickObs$suspend)

## Data Explorer ###########################################
  observe({
    counties <- if (is.null(input$states)) character(0) else {
      wholedata %>% 
        filter(state %in% input$states) %>%
        `$`('county') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$counties[input$counties %in% counties])
    updateSelectizeInput(session, "counties", choices = counties,
      selected = stillSelected, server = TRUE)
  })

  observe({
    systems <- if (is.null(input$states)) character(0) else {
     wholedata %>%
        filter(state %in% input$states,
          is.null(input$counties) | county %in% input$counties) %>%
        `$`('system') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$systems[input$systems %in% systems])
    updateSelectizeInput(session, "systems", choices = systems,
      selected = stillSelected, server = TRUE)
  })

  output$systable <- DT::renderDataTable({
    df <- wholedata %>%
      filter(
        year>=input$Y[1]&year<=input$Y[2],
        min_stop_dist >= input$Dist[1]& min_stop_dist<= input$Dist[2],
        is.null(input$states) | state %in% input$states,
        is.null(input$counties) | county %in% input$counties,
        is.null(input$systems) | system %in% input$systems
      )

    DT::datatable(df, escape = FALSE)
  })

})

```


```{r}
## UI Setup
library(leaflet)
library(shiny)

# Choices for drop-downs
vars <- c(
  "Is Treated Borrower?" = "Treat",
  "Distance to Nearest Roadshow Stop " = "min_stop_dist",
  "Energy Consumption" = "EnergyConsump",
  "Allotment" = "allo_all",
  "Operation Revenue" = "re_opm"
)

years <- c("1941","1942","1943","1944","1945", "1946")

ui <- shinyUI(navbarPage("REA Data", id="nav",

  tabPanel("Interactive map",
    div(class="outer",

      # If not using custom CSS, set height of leafletOutput to a number instead of percent
    leafletOutput("map", width="768", height="480"),

      # Shiny versions prior to 0.11 should use class = "modal" instead.
      absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE, draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto", width = 330, height = "auto",

        h2("READata explorer"),
        
        selectInput("year", "Data Year", years, selected= "1943"),

        selectInput("color", "Color", vars),
        selectInput("size", "Size", vars, selected = "EnergyConsump"),
        conditionalPanel("input.color == 'Treat'",
          # Only prompt for threshold when coloring by superzip
        numericInput("threshold", "Distance threshold (miles)", 20)),
        
        plotOutput("histEnergy", height = 200),
        plotOutput("scatterStopEnergy", height = 250)
        
      ),
    )
  ),
  
  tabPanel("Data explorer",
    fluidRow(
    column(2,
      sliderInput("Y", label = h4("Data Year"), min = 1941, 
        max = 1946, value = c(1942, 1944))
      )
    ),
    hr(),
    fluidRow(
      column(3,
        selectInput("states", "States", c("All states"="", structure(state.abb, names=state.name)), multiple=TRUE)
      ),
      column(3,
        conditionalPanel("input.states",
          selectInput("counties", "Counties", c("All counties"=""), multiple=TRUE)
        )
      ),
      column(3,
        conditionalPanel("input.states",
          selectInput("systems", "Systems", c("All systems"=""), multiple=TRUE)
        )
      )
    ),
    hr(),
    fluidRow(
    column(10,
      sliderInput("Dist", label = h4("Distance to Nearest Stop"), min = 0, 
        max = 800, value = c(0, 40))
      )
    ),
    hr(),
    DT::dataTableOutput("systable")
  ),

  conditionalPanel("false", icon("crosshair"))
))
```

```{r}
# Create Shiny app ----
shinyApp(ui = ui, server = server)
```